apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base/external-secrets-crd


components:
- ../../env/shared-services/external-secrets-crd