---
apiVersion: v1
kind: Namespace
metadata:
  name: iris-green

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-flux-reconciler
  namespace: iris-green

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iris-green-reconciler
  namespace: iris-green
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metatmc-controller-role
subjects:
- kind: ServiceAccount
  name: tenant-flux-reconciler
  namespace: iris-green



---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: iris-green
  namespace: iris-green
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/warroyo/iris-green-gitops


## every cluster that this tenant is on should have a kustomization and a TMCNamespace
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: iris-green-dev
  namespace: iris-green
spec:
  interval: 10m0s
  path: ./clusters/iris-dev/namespaces
  prune: true
  serviceAccountName: tenant-flux-reconciler
  targetNamespace: iris-green
  sourceRef:
    kind: GitRepository
    name: iris-green
  patches:
    - patch: |-
        apiVersion: tmc.tanzufield.vmware.com/v1
        kind: TMCNamespace
        metadata:
          name: not used
        spec:
          fullName:
            clusterName: eks.eks-warroyo2.us-west-2.iris-dev
            managementClusterName: eks
            provisionerName: eks
          spec:
            workspaceName: iris-green
                  
      target:
        kind: TMCNamespace

---
apiVersion: tmc.tanzufield.vmware.com/v1
kind: TMCNamespace
metadata:
  name: iris-green
  namespace: iris-green
  labels:
    version: v1
spec:
  fullName:
    name: iris-green
    clusterName: eks.eks-warroyo2.us-west-2.iris-dev
    managementClusterName: eks
    provisionerName: eks
  meta:
    labels:
      team: iris-green
  spec:
    workspaceName: iris-green    
