# Default values for tenant-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster_name: changeme
tenants:
  - name: changeme2
    namespace: ""
    git_repo_url: https://changeme
