apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base/external-secrets-crd/css.yml
- ../../base/contour
- ../../base/external-dns


components:
- ../../env/dev/external-secrets-crd

patches:
- target:
    group: packaging.carvel.dev
    version: v1alpha1
    kind: PackageInstall
    name: contour
  patch: |-
    - op: add
      path: /spec/values/1
      value: {
          "secretRef": {"name": "contour-packages-values-overrides"}
            }
- target:
    group: packaging.carvel.dev
    version: v1alpha1
    kind: PackageInstall
    name: external-dns
  patch: |-
    - op: add
      path: /spec/values/1
      value: {
          "secretRef": {"name": "external-dns-packages-values-overrides"}
            }
secretGenerator:
- name: external-dns-packages-values-overrides
  namespace: infra-packages
  files:
  - external-dns-values.yml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: external-dns-packages