apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base/external-secrets-crd/css.yml
- ../../base/metacontroller/install.yml
- ../../base/tmc-controller/install.yml


components:
- ../../env/shared-services/external-secrets-crd